name: WordPress Plugin asset/readme update

on:
  push:
    branches:
      - 'svn-trunk'

jobs:
  trunk:
    name: Push to trunk on WordPress.org via SVN
    runs-on: ubuntu-18.04
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
